services:
  db:
    image: postgres:15-alpine
    container_name: workforce-db-dev
    environment:
      POSTGRES_DB: workforce_os
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:7-alpine
    container_name: workforce-redis-dev
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: workforce-mq-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
